-- README.sql (psql-friendly)
--
-- Recommended apply order:
--   psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f 00_extensions.sql
--   psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f 01_enums.sql
--   psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f 02_tables.sql
--   psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f 03_indexes.sql
--   psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f 04_triggers.sql
--   psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f 05_views.sql
--
-- Notes:
-- - Invariants enforced here align with v1 docs:
--   * RSVP only for PUBLISHED trips; capacity enforced on YES
--   * at least one organizer must always exist
--   * draft visibility only for DRAFTs
--   * publish-time required fields enforced on transition to PUBLISHED
